#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
	enum class WINMODE { FULL, WIN, END };	
	enum class PROTOTYPE { GAMEOBJECT, COMPONENT };
	enum class STATE { RIGHT, UP, LOOK, POSITION, END };
	enum class LIGHT { DIRECTIONAL, POINT, SPOT, END };
	enum class RENDER { PRIORITY, SHADOW, NONBLEND, BLUR, BLEND, NONLIGHT, WORLDUI, UI, CURSOR, END};
	enum class TEXTURE { DIFFUSE, NORMAL, SPECULAR, EMISSIVE, REFLECTION, MASK, COLOR_FX, ORM, NONE, DIFFUSE_SEAMLESS, NORMAL_SEAMLESS,END };
	enum class MODEL {NONANIM, ANIM, MESH};
	enum class COLLIDER {AABB, OBB, SPHERE, END};
	enum class COLLIDERTYPE { COLLIDER, HITBOX, END};
	enum class RAY { LOCAL, WORLD, END };
	enum class CHANNELID { BGM, SKILL_PLAYER, SKILL_MONSTER, SKILL_BOSS0, SKILL_BOSS1, SKILL_BOSS2, HIT_PLAYER, HIT_MONSTER, EFFECT, SYSTEM, END };
	enum class D3DTS {VIEW, PROJ, END};
	enum class MOUSEKEYSTATE { LBUTTON, RBUTTON, WBUTTON, XBUTTON };
	enum class MOUSEMOVESTATE { X, Y, W };
	enum class MOUSESPACE { VIEWPORT, PROJ, VIEW, WORLD, LOCAL };
	enum class LERP {LINEAR, EASEIN, EASEOUT, EASEINOUT};
	enum class PARTICLE {SPREAD, SCALE, CIRCLE, ROUND, CORN, UP};
}
#endif // Engine_Enum_h__
