#pragma once

#include <process.h>
#include <fstream>
#include "../Default/framework.h"

constexpr float MAX_IDENTITY = 120.f;

namespace Client
{

	const unsigned int g_iWinSizeX = 1280;
	const unsigned int g_iWinSizeY = 720;

	enum class LEVEL { STATIC, LOADING, LOGO, GAMEPLAY, TUTORIAL, BOSS, MAP_EDITOR, END};
	enum class STANCE {FLURRY, FOCUS, IDEN_END};
	enum class MONSTER { NORMAL, NAMED, BOSS };
	enum class CAMERA_ANIM { IDLE, SHAKE, ZOOMOUT, INTOR_BOSS };
	enum class PHASE { INTRO, PHASE1, PHASE2, PHASE3, END };

	enum class ATTACK_TYPE {NORMAL, HEAD, BACK};
	enum class HIT_TYPE { NORMAL, PUSH, FLOAT };

	enum SKILL_TYPE { SKILL_NORAML, SKILL_COMBO, SKILL_POINT, SKILL_CHARGE };
	enum STAGGER { STAGGER_NONE, STAGGER_LOW, STAGGER_MIDDLE, STAGGER_HIGH };
	enum PART_BREAKER { PART_BREAKER_NONE, PART_BREAKER_LOW, PART_BREAKER_MID, PART_BREAKER_HIGH};
	enum SUPER_ARMOUR {
		SUPRE_ARMOUR_NONE = 0,
		SUPRE_ARMOUR_PARALYSIS = 1 << 1,
		SUPRE_ARMOUR_PUSH = 1 << 2,
		SUPRE_ARMOUR_ALL = SUPRE_ARMOUR_PARALYSIS | SUPRE_ARMOUR_PUSH
	};
	
	enum class ANIMATIONSLOT {
		RESPAWN,
		IDLE, IDLE_BATTLE,
		WALK, RUN, TURN_R, TURN_L,
		DEAD, DEAD_LOOP,
		ATTACK_1, ATTACK_2, ATTACK_3, ATTACK_4, ATTACK_5,
		CRITICAL_START, CRITICAL_LOOP, CRITICAL_END,
		BOUND, BOUND_HIT, BOUND_LAND, GROUND,
		STANDUP, KNOKDOWN, KNOKDOWN_LAND, TWIST_KNOCKDOWN, TWIST_KNOCKDOWN_LAND,
		END
	};
}

using namespace Client;

extern HINSTANCE g_hInstance;
extern HWND g_hWnd;